import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';

import '@/styles/globals.css';

import { cn } from '@/lib/utils';

import { Toaster } from '@/components/ui/sonner';

import { TRPCReactProvider } from '@/trpc/react';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans text-foreground antialiased',
          GeistSans.variable,
          GeistMono.variable,
        )}
      >
        <TRPCReactProvider>
          {children}
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
